[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "mortie"
dynamic = ["version"]

[tool.setuptools_scm]
version_file = "mortie/_version.py"
